package tui

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"taskctl/core"
	"time"
)

// ExportProcess exports a process as Markdown file
func ExportProcess(processID uint) (string, error) {
	exportData, err := core.GetProcessContext(processID)
	if err != nil {
		return "", err
	}

	// Generate Markdown content
	md := generateMarkdown(exportData)

	// Determine output path
	filename := fmt.Sprintf("%s-%d.md",
		strings.ToLower(strings.ReplaceAll(exportData.Process.Title, " ", "-")),
		exportData.Process.ID)

	outputPath := filename

	// Write to file
	if err := os.WriteFile(outputPath, []byte(md), 0644); err != nil {
		return "", err
	}

	return outputPath, nil
}

// generateMarkdown generates Markdown content from ProcessExport
func generateMarkdown(export *core.ProcessExport) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# ")
	sb.WriteString(export.Process.Title)
	sb.WriteString("\n\n")

	// Metadata
	sb.WriteString("**Status:** ")
	sb.WriteString(string(export.Process.Status))
	sb.WriteString(" | **Priority:** ")
	sb.WriteString(string(export.Process.Priority))
	sb.WriteString(" | **Created:** ")
	sb.WriteString(export.Process.CreatedAt.Format("2006-01-02 15:04"))
	if export.Process.Status == core.StatusTerminated {
		sb.WriteString(" → ")
		sb.WriteString(export.Process.UpdatedAt.Format("2006-01-02 15:04"))
	}
	sb.WriteString("\n\n")

	// Description
	if export.Process.Description != "" {
		sb.WriteString("## Description\n\n")
		sb.WriteString(export.Process.Description)
		sb.WriteString("\n\n")
	}

	// Timeline
	sb.WriteString("## Timeline\n\n")

	for _, log := range export.Logs {
		timestamp := log.CreatedAt.Format("2006-01-02 15:04")
		icon := getLogIconMarkdown(log.LogType)

		sb.WriteString(fmt.Sprintf("### %s %s\n\n", timestamp, icon))
		sb.WriteString(log.Content)
		sb.WriteString("\n\n")
	}

	// Children
	if len(export.Children) > 0 {
		sb.WriteString("## Sub-processes\n\n")
		for _, child := range export.Children {
			sb.WriteString(fmt.Sprintf("- [%s](%s-%d.md)\n",
				child.Process.Title,
				strings.ToLower(strings.ReplaceAll(child.Process.Title, " ", "-")),
				child.Process.ID))
		}
		sb.WriteString("\n")
	}

	// Footer
	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("*Generated by taskctl on %s*\n", time.Now().Format("2006-01-02 15:04:05")))

	return sb.String()
}

// getLogIconMarkdown returns emoji icon for log type
func getLogIconMarkdown(logType core.LogType) string {
	switch logType {
	case core.LogTypeStateChange:
		return "🔄"
	case core.LogTypeProgress:
		return "📝"
	default:
		return "📌"
	}
}

// GenerateExportFileName generates the filename for export preview
func GenerateExportFileName(process *core.Process) string {
	return fmt.Sprintf("%s-%d.md",
		strings.ToLower(strings.ReplaceAll(process.Title, " ", "-")),
		process.ID)
}

// GetAbsolutePath returns the absolute path for a filename
func GetAbsolutePath(filename string) string {
	if filepath.IsAbs(filename) {
		return filename
	}
	abs, err := filepath.Abs(filename)
	if err != nil {
		return filename
	}
	return abs
}
