package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"taskctl/core"
	"time"
	"github.com/spf13/cobra"
)

var (
	exportDir string
)

var exportCmd = &cobra.Command{
	Use:   "export <id>",
	Short: "Export process as Markdown",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id, err := strconv.ParseUint(args[0], 10, 32)
		if err != nil {
			return fmt.Errorf("invalid process ID: %w", err)
		}

		exportData, err := core.GetProcessContext(uint(id))
		if err != nil {
			return err
		}

		// Generate Markdown content
		md := generateMarkdown(exportData)

		// Determine output path
		filename := fmt.Sprintf("%s-%d.md",
			strings.ToLower(strings.ReplaceAll(exportData.Process.Title, " ", "-")),
			exportData.Process.ID)

		var outputPath string
		if exportDir != "" {
			outputPath = filepath.Join(exportDir, filename)
			// Create directory if it doesn't exist
			if err := os.MkdirAll(exportDir, 0755); err != nil {
				return err
			}
		} else {
			outputPath = filename
		}

		// Write to file
		if err := os.WriteFile(outputPath, []byte(md), 0644); err != nil {
			return err
		}

		fmt.Printf("Exported process #%d to: %s\n", exportData.Process.ID, outputPath)
		return nil
	},
}

func generateMarkdown(export *core.ProcessExport) string {
	var sb strings.Builder

	// Header
	sb.WriteString("# ")
	sb.WriteString(export.Process.Title)
	sb.WriteString("\n\n")

	// Metadata
	sb.WriteString("**Status:** ")
	sb.WriteString(string(export.Process.Status))
	sb.WriteString(" | **Priority:** ")
	sb.WriteString(string(export.Process.Priority))
	sb.WriteString(" | **Created:** ")
	sb.WriteString(export.Process.CreatedAt.Format("2006-01-02 15:04"))
	if export.Process.Status == core.StatusTerminated {
		sb.WriteString(" → ")
		sb.WriteString(export.Process.UpdatedAt.Format("2006-01-02 15:04"))
	}
	sb.WriteString("\n\n")

	// Description
	if export.Process.Description != "" {
		sb.WriteString("## Description\n\n")
		sb.WriteString(export.Process.Description)
		sb.WriteString("\n\n")
	}

	// Timeline
	sb.WriteString("## Timeline\n\n")

	for _, log := range export.Logs {
		timestamp := log.CreatedAt.Format("2006-01-02 15:04")
		icon := getLogIconMarkdown(log.LogType)

		sb.WriteString(fmt.Sprintf("### %s %s\n\n", timestamp, icon))
		sb.WriteString(log.Content)
		sb.WriteString("\n\n")
	}

	// Children
	if len(export.Children) > 0 {
		sb.WriteString("## Sub-processes\n\n")
		for _, child := range export.Children {
			sb.WriteString(fmt.Sprintf("- [%s](%s-%d.md)\n",
				child.Process.Title,
				strings.ToLower(strings.ReplaceAll(child.Process.Title, " ", "-")),
				child.Process.ID))
		}
		sb.WriteString("\n")
	}

	// Footer
	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("*Generated by taskctl on %s*\n", time.Now().Format("2006-01-02 15:04:05")))

	return sb.String()
}

func getLogIconMarkdown(logType core.LogType) string {
	switch logType {
	case core.LogTypeStateChange:
		return "🔄"
	case core.LogTypeProgress:
		return "📝"
	default:
		return "📌"
	}
}

func init() {
	rootCmd.AddCommand(exportCmd)
	exportCmd.GroupID = GroupUI
	exportCmd.Flags().StringVarP(&exportDir, "dir", "D", "", "Output directory")
}
